@echo off
echo Starting VenueVoice Development Environment...
echo Killing any existing Node processes...
taskkill /F /IM node.exe 2>nul || echo No existing processes found
echo Cleaning build cache...
cd apps\frontend
if exist ".next" rmdir /s /q ".next"
echo Installing dependencies...
call npm install
echo Starting servers...
start "Voice Server" cmd /c "npm run dev:voice"
timeout /t 3 /nobreak >nul
start "Next.js Server" cmd /c "npm run dev"
echo Both servers are starting...
echo Voice Server: ws://localhost:8787
echo Next.js Server: http://localhost:3000
echo.
echo Press any key to close...
pause
